### ISSUE TITLE
[Request] random_account return dictionary

### ISSUE THREAD

**Issue by Ashex** [jepayne1138/PTCAccount#5]
Currently an ordered list is returned which works _but_ it'd be better if a named dictionary were used. 

``` python
return {'user': try_username, 'password': password, 'email': try_email}
```

**Comment by jepayne1138** [comment]
I thought that was supposed to close this issue, but perhaps the 'closes' keyword in the commit is case sensitive or something.  In any case, I concur that a dict is a better design decision, and have made the change for future versions.
