### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by noziv** [jepayne1138/PTCAccount#7]
Hey everytime i try your script i get an error:
`G:\Users\noziv\AppData\Local\Programs\Python\Python35-32\Scripts>ptc --email=tes
tserveur@gmail.com --email-tag
Traceback (most recent call last):
  File "G:\Users\noziv\AppData\Local\Programs\Python\Python35-32\Scripts\ptc-scr
ipt.py", line 9, in <module>
    load_entry_point('PTCAccount==1.2.1', 'console_scripts', 'ptc')()
  File "g:\users\noziv\appdata\local\programs\python\python35-32\lib\site-packag
es\ptcaccount\console.py", line 45, in entry
    args.username, args.password, args.email, args.email_tag
ValueError: too many values to unpack (expected 3)
`
Problem is that when i don't use --email-tag and insert a custom user, password and email I get this error too. I get the verification email, so the account is created but with a random password that i can't see because of the error.

Btw, thanks for this script :)

**Comment by jepayne1138** [comment]
Changed the return signature of the random_account function and forgot to update the automatic unpacking in the console command.  Thanks for bringing this to my attention.  This is what I get for not properly testing, but to be honest I didn't expect people to actually use it, so I didn't put too much time into it.  Thanks for checking it out.
